base_controller:
  caster_names: fr_caster_rotation_link fl_caster_rotation_link bl_caster_rotation_link br_caster_rotation_link

  type:  pr2_mechanism_controllers/Pr2BaseController2
  publish_tf: false

  f_caster_velocity_pid_gains: &f_caster_velocity_pid_gains
    p: 8.0
    d: 0.0
    i: 0.0
    i_clamp: 4.0

  f_caster_position_pid_gains: &f_caster_position_pid_gains
    p: 100.0
    d: 8.0
    i: 0.0
    i_clamp: 0.0

  b_caster_velocity_pid_gains: &b_caster_velocity_pid_gains
    p: 8.0
    d: 0.0
    i: 0.0
    i_clamp: 4.0

  b_caster_position_pid_gains: &b_caster_position_pid_gains
    p: 100.0
    d: 12.0
    i: 0.0
    i_clamp: 0.0

  wheel_pid_gains: &wheel_pid_gains
    p: 100.0
    d: 5.0
    i: 0.0
    i_clamp: 0.0

  fl_caster_l_wheel_joint:
   *wheel_pid_gains
  fl_caster_r_wheel_joint:
   *wheel_pid_gains
  fr_caster_l_wheel_joint:
   *wheel_pid_gains
  fr_caster_r_wheel_joint:
   *wheel_pid_gains
  bl_caster_l_wheel_joint:
   *wheel_pid_gains
  bl_caster_r_wheel_joint:
   *wheel_pid_gains
  br_caster_l_wheel_joint:
   *wheel_pid_gains
  br_caster_r_wheel_joint:
   *wheel_pid_gains

  fr_caster_rotation_joint:
   velocity_controller:
    *f_caster_velocity_pid_gains
   position_controller:
    *f_caster_position_pid_gains
  fl_caster_rotation_joint:
   velocity_controller:
    *f_caster_velocity_pid_gains
   position_controller:
    *f_caster_position_pid_gains
  bl_caster_rotation_joint:
   velocity_controller:
    *b_caster_velocity_pid_gains
   position_controller:
    *b_caster_position_pid_gains
  br_caster_rotation_joint:
   velocity_controller:
    *b_caster_velocity_pid_gains
   position_controller:
    *b_caster_position_pid_gains

  timeout: 0.2
  max_translational_acceleration: 
   x: 2.0
   y: 2.0 
  max_rotational_acceleration: 2.0
  state_publish_rate: 0.25

  max_translational_velocity: 1.0 
  max_rotational_velocity: 2.0

  caster_velocity_filter:
   name: caster_velocity_filter
   type: filters/MultiChannelTransferFunctionFilterDouble
   params:
    a: [1.0, -0.5]
    b: [0.5]

  wheel_velocity_filter:
   name: wheel_velocity_filter
   type: filters/MultiChannelTransferFunctionFilterDouble
   params:
    a: [1.0, -0.5]
    b: [0.5]
