r_shoulder_pan_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: r_shoulder_pan_joint
  pid: &shoulder_pan_position_gains
    p: 2400.0
    d: 18.0
    i: 800.0
    i_clamp: 4.0
r_shoulder_lift_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: r_shoulder_lift_joint
  pid: &shoulder_lift_position_gains
    p: 1200.0
    d: 10.0
    i: 700.0
    i_clamp: 4.0
r_upper_arm_roll_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: r_upper_arm_roll_joint
  pid: &upper_arm_roll_position_gains
    p: 1000.0
    d: 6.0
    i: 600.0
    i_clamp: 4.0
r_elbow_flex_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: r_elbow_flex_joint
  pid: &elbow_flex_position_gains
    p: 700.0
    d: 4.0
    i: 450.0
    i_clamp: 4.0
r_forearm_roll_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: r_forearm_roll_joint
  pid: &forearm_roll_position_gains
    p: 300.0
    d: 6.0
    i: 300.0
    i_clamp: 2.0
r_wrist_flex_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: r_wrist_flex_joint
  pid: &wrist_flex_position_gains
    p: 300.0
    d: 4.0
    i: 300.0
    i_clamp: 2.0
r_wrist_roll_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: r_wrist_roll_joint
  pid: &wrist_roll_position_gains
    p: 300.0
    d: 4.0
    i: 300.0
    i_clamp: 2.0
r_gripper_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: r_gripper_joint
  pid: &gripper_position_gains
    p: 1000
    d: 0.0
    i: 0.0
    i_clamp: 0.0

l_shoulder_pan_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: l_shoulder_pan_joint
  pid: *shoulder_pan_position_gains
l_shoulder_lift_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: l_shoulder_lift_joint
  pid: *shoulder_lift_position_gains
l_upper_arm_roll_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: l_upper_arm_roll_joint
  pid: *upper_arm_roll_position_gains
l_elbow_flex_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: l_elbow_flex_joint
  pid: *elbow_flex_position_gains
l_forearm_roll_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: l_forearm_roll_joint
  pid: *forearm_roll_position_gains
l_wrist_flex_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: l_wrist_flex_joint
  pid: *wrist_flex_position_gains
l_wrist_roll_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: l_wrist_roll_joint
  pid: *wrist_roll_position_gains
l_gripper_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: l_gripper_joint
  pid: *gripper_position_gains

torso_lift_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: torso_lift_joint
  pid:
    p: 10000000.0
    d: 1000000.0
    i: 0.0
    i_clamp: 0.0
