r_shoulder_pan_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: r_shoulder_pan_joint
  pid: &shoulder_pan_velocity_gains
    p: 30
    i: 4.67
    d: 0.0
    i_clamp: 100.0
r_shoulder_lift_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: r_shoulder_lift_joint
  pid: &shoulder_lift_velocity_gains
    p: 30.0
    i: 5.67
    d: 0
    i_clamp: 100.0
r_upper_arm_roll_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: r_upper_arm_roll_joint
  pid: &upper_arm_roll_velocity_gains
    p: 7
    i: 42.9
    d: 0
    i_clamp: 100.0
r_elbow_flex_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: r_elbow_flex_joint
  pid: &elbow_flex_velocity_gains
    p: 5
    i: 20.0
    d: 0
    i_clamp: 100.0
r_forearm_roll_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: r_forearm_roll_velocity
  pid: &forearm_roll_velocity_gains
    p: 20.0
    i: 15.0
    d: 0
    i_clamp: 100.0
r_wrist_flex_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: r_wrist_flex_joint
  pid: &wrist_flex_velocity_gains
    p: 8.0
    i: 25.0
    d: 0
    i_clamp: 100.0
r_wrist_roll_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: r_wrist_roll_joint
  pid: &wrist_roll_velocity_gains
    p: 8.0
    i: 25.0
    d: 0
    i_clamp: 100.0



l_shoulder_pan_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: l_shoulder_pan_joint
  pid: *shoulder_pan_velocity_gains
l_shoulder_lift_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: l_shoulder_lift_joint
  pid: *shoulder_lift_velocity_gains
l_upper_arm_roll_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: l_upper_arm_roll_joint
  pid: *upper_arm_roll_velocity_gains
l_elbow_flex_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: l_elbow_flex_joint
  pid: *elbow_flex_velocity_gains
l_forearm_roll_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: l_forearm_roll_velocity
  pid: *forearm_roll_velocity_gains
l_wrist_flex_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: l_wrist_flex_joint
  pid: *wrist_flex_velocity_gains
l_wrist_roll_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: l_wrist_roll_joint
  pid: *wrist_roll_velocity_gains


torso_lift_velocity_controller:
  type: robot_mechanism_controllers/JointVelocityController
  joint: torso_lift_joint
  pid: &torso_lift_velocity_gains
    p: 2000000.0
    d: 0.0
    i: 1000.0
    i_clamp: 1200.0



