head_traj_controller:
  type: robot_mechanism_controllers/JointTrajectoryActionController
  joints: ['head_pan_joint', 'head_tilt_joint']
  gains:
    head_pan_joint:
      p: 25.0
      i: 12.0
      d: 2.0
      i_clamp: 0.5 
    head_tilt_joint:
      p: 49.6
      i: 2.0
      d: 1.6
      i_clamp: 0.1 
